/* js/data.js */
window.CL = window.CL || {};

window.CL.data = {

  currentUser: {
    name:    'Juniel Cardenas',
    title:   'Frontend Developer',
    email:   'cardenas.juniel.permito@gmail.com',
    phone:   '+63 912 345 6789',
    location:'Quezon City, Metro Manila',
    avatar:  './pfp.jfif',
    summary: 'Passionate frontend developer with 3 years of experience building responsive web apps using Vue.js and React. I value clean code, great UX, and continuous learning.',
    skills:  ['Vue.js','React','TypeScript','Tailwind CSS','PHP / Laravel','MySQL','Git','Figma'],
    completion: 82,
  },

  currentCompany: {
    name:     'TechBridge Philippines',
    industry: 'Information Technology',
    size:     '51–200 employees',
    about:    'TechBridge Philippines is a leading software development company specializing in enterprise web applications and digital transformation solutions.',
    avatar:   'https://i.pravatar.cc/150?img=11',
    logoColor:'#2563eb',
    initials: 'TB',
  },

  jobs: [
    { id:1, title:'Senior Frontend Developer', company:'TechBridge Philippines', logoColor:'#2563eb', initials:'TB', avatar:'https://i.pravatar.cc/150?img=11', location:'BGC, Taguig City', salary:'₱80,000–₱120,000', period:'Monthly', type:'Full Time', arrangement:'Hybrid', category:'Technology', posted:'2 days ago', saved:true,
      desc: "Lead the development of our next-generation SaaS platform. You'll collaborate closely with product, backend, and design to deliver high-quality, scalable web interfaces used by over 2,000 Philippine companies.",
      reqs:['3+ years of experience with Vue.js or React','Strong proficiency in TypeScript and modern CSS','Experience with REST APIs and GraphQL','Familiarity with CI/CD pipelines and code review culture'],
      perks:['Competitive salary + equity','HMO coverage for 2 dependents','Hybrid setup — 3 days WFH','₱30,000 signing bonus','Annual learning & development budget'],
    },
    { id:2, title:'Customer Service Representative', company:'Accenture Philippines', logoColor:'#a21caf', initials:'AC', avatar:'https://i.pravatar.cc/150?img=12', location:'Alabang, Muntinlupa', salary:'₱18,000–₱22,000', period:'Monthly', type:'Full Time', arrangement:'On-site', category:'BPO / Call Center', posted:'1 day ago', saved:false,
      desc:'Join our world-class BPO team supporting a top US financial services client. Handle inbound calls, resolve customer inquiries, and deliver exceptional service.',
      reqs:['Strong spoken and written English','At least Senior High School graduate','Willing to work night shifts','Basic computer literacy'],
      perks:['Night differential pay','Complete government benefits','Paid product and process training','Career advancement pathways'],
    },
    { id:3, title:'Senior Graphic Designer', company:'Creative Spark Agency', logoColor:'#ea580c', initials:'CS', avatar:'https://i.pravatar.cc/150?img=13', location:'Quezon City (Remote)', salary:'₱35,000–₱50,000', period:'Monthly', type:'Full Time', arrangement:'Remote', category:'Design & Creative', posted:'3 days ago', saved:true,
      desc:'Create compelling visuals for our diverse portfolio across FMCG, tech, and lifestyle brands. Full creative freedom and a collaborative, remote-first culture.',
      reqs:['5+ years graphic design experience','Expert in Adobe Creative Suite (Ps, Ai, Id)','Strong portfolio in brand identity','Motion graphics experience is a plus'],
      perks:['100% remote work','Flexible hours','₱5,000 monthly tool allowance','Annual design conference sponsorship','13th month + performance bonus'],
    },
    { id:4, title:'Data Analyst', company:'Globe Telecom', logoColor:'#0284c7', initials:'GT', avatar:'https://i.pravatar.cc/150?img=15', location:'Mandaluyong City', salary:'₱50,000–₱70,000', period:'Monthly', type:'Full Time', arrangement:'Hybrid', category:'Technology', posted:'5 days ago', saved:false,
      desc: "Join Globe's Business Intelligence team to transform raw telecom data into insights that drive millions of customer experiences across the Philippines.",
      reqs:['Degree in Statistics, Math, CS, or related field','Proficient in SQL and Python or R','Experience with Tableau or Power BI','Strong communication and storytelling skills'],
      perks:['HMO for you and dependents','Stock option plan','Annual merit increase','Gym membership subsidy'],
    },
    { id:5, title:'Digital Marketing Specialist', company:'Shopee Philippines', logoColor:'#dc2626', initials:'SP', avatar:'https://i.pravatar.cc/150?img=16', location:'Pasig City', salary:'₱35,000–₱50,000', period:'Monthly', type:'Full Time', arrangement:'On-site', category:'Marketing', posted:'1 week ago', saved:true,
      desc: "Own performance marketing campaigns, manage KOL partnerships, and analyze campaign effectiveness across Meta, Google, and TikTok for one of SE Asia's largest e-commerce platforms.",
      reqs:['2+ years digital marketing experience','Hands-on with Meta Ads and Google Ads','Strong data-driven decision mindset','SEO/SEM experience preferred'],
      perks:['Employee shopping discounts','Flexible PTO','Birthday leave','Annual team offsite','Quarterly performance bonus'],
    },
    { id:6, title:'UX / UI Designer', company:'Lamudi Philippines', logoColor:'#16a34a', initials:'LP', avatar:'https://i.pravatar.cc/150?img=17', location:'Makati City (Remote)', salary:'₱50,000–₱75,000', period:'Monthly', type:'Full Time', arrangement:'Remote', category:'Design & Creative', posted:'4 days ago', saved:false,
      desc:'Shape the digital property search experience for millions of Filipinos. Own end-to-end UX for our web and mobile apps — from user research through high-fidelity prototypes.',
      reqs:['3+ years UX/UI design experience','Expert in Figma','Mobile and web case studies in portfolio','Experience facilitating user interviews'],
      perks:['Full remote','₱3,000 monthly internet allowance','Unlimited PTO','HMO + dental coverage','Annual UX conference ticket'],
    },
    { id:7, title:'Java Backend Developer', company:'UnionBank of the Philippines', logoColor:'#d97706', initials:'UB', avatar:'https://i.pravatar.cc/150?img=18', location:'Ortigas, Pasig City', salary:'₱70,000–₱100,000', period:'Monthly', type:'Full Time', arrangement:'Hybrid', category:'Technology', posted:'2 days ago', saved:false,
      desc: "Develop robust, secure backend services powering mobile banking, lending, and payments for millions of Filipinos as part of UnionBank's digital transformation.",
      reqs:['4+ years Java development','Strong Spring Boot experience','Knowledge of microservices architecture','Familiarity with banking regulations a plus'],
      perks:['HMO for whole family','Annual performance bonus','Tuition reimbursement','Employee banking privileges'],
    },
    { id:8, title:'Content Writer & SEO Specialist', company:'Summit Media Group', logoColor:'#7c3aed', initials:'SM', avatar:'https://i.pravatar.cc/150?img=20', location:'Mandaluyong City', salary:'₱25,000–₱35,000', period:'Monthly', type:'Full Time', arrangement:'Hybrid', category:'Marketing', posted:'6 days ago', saved:true,
      desc: "Create SEO-optimized content across the Philippines' most-read digital media brands, from product reviews and listicles to long-form features.",
      reqs:['Excellent written English','Solid understanding of on-page SEO','1+ year content writing experience','Proficiency with WordPress or similar CMS'],
      perks:['Free magazine subscriptions','Hybrid work schedule','Health insurance','₱2,000 monthly creative allowance'],
    },
    { id:9, title:'Sales Executive — Property', company:'Ayala Land', logoColor:'#0f766e', initials:'AL', avatar:'https://i.pravatar.cc/150?img=21', location:'Makati City', salary:'₱30,000 + Commission', period:'Monthly', type:'Full Time', arrangement:'On-site', category:'Sales', posted:'3 days ago', saved:false,
      desc: "Represent one of the Philippines' most trusted real estate brands, guiding clients through property acquisitions from affordable housing to premium residential developments.",
      reqs:['Strong consultative sales skills','Real estate broker license or willing to obtain','Excellent interpersonal and presentation skills'],
      perks:['Uncapped commission','Car allowance after 6 months','Employee property discount','Annual sales incentive trips'],
    },
    { id:10, title:'Virtual Assistant — Executive Support', company:'Outsource Accelerator', logoColor:'#0891b2', initials:'OA', avatar:'https://i.pravatar.cc/150?img=22', location:'Fully Remote', salary:'₱20,000–₱30,000', period:'Monthly', type:'Full Time', arrangement:'Remote', category:'Admin & HR', posted:'1 day ago', saved:false,
      desc:'Support a fast-growing Australian CEO with calendar management, email triage, travel coordination, and research. Long-term role with a clear path to Senior Executive VA.',
      reqs:['2+ years VA or executive assistant experience','Excellent written and spoken English','Proficient in Google Workspace and Notion','Self-starter, strong time management'],
      perks:['Permanently remote','Australian client premium rates','Annual salary review','10 days paid leave','Equipment allowance'],
    },
    { id:11, title:'DevOps / Cloud Engineer', company:'Sprout Solutions', logoColor:'#059669', initials:'SS', avatar:'https://i.pravatar.cc/150?img=25', location:'Makati City (Remote)', salary:'₱80,000–₱120,000', period:'Monthly', type:'Full Time', arrangement:'Remote', category:'Technology', posted:'1 week ago', saved:true,
      desc:'Own our AWS infrastructure supporting 2,000+ Philippine companies. Automate deployments, ensure 99.9% uptime, and help scale our HRIS platform.',
      reqs:['3+ years DevOps experience','Strong AWS knowledge (EC2, EKS, RDS, S3)','Proficiency in Terraform / Ansible','Experience with Docker and Kubernetes'],
      perks:['Full remote','Laptop + home office allowance','AWS certification reimbursement','Quarterly performance bonus'],
    },
    { id:12, title:'HR & Recruitment Coordinator', company:'SM Retail', logoColor:'#be185d', initials:'SM', avatar:'https://i.pravatar.cc/150?img=26', location:'Pasay City', salary:'₱22,000–₱28,000', period:'Monthly', type:'Full Time', arrangement:'On-site', category:'Admin & HR', posted:'5 days ago', saved:false,
      desc: "Support end-to-end recruitment for one of the Philippines' largest retail employers — coordinating interviews, maintaining HR records, and onboarding associates across Metro Manila stores.",
      reqs:['Degree in HR, Psychology, or Business','1+ year HR or recruitment experience','Proficient in MS Office','Experience with ATS software a plus'],
      perks:['SM employee discount card','Complete government benefits','Retirement plan','SM scholarship for dependents'],
    },
  ],

  appliedJobs: [
    { title:'Senior Frontend Developer',       company:'TechBridge Philippines', logoColor:'#2563eb', initials:'TB', date:'Mar 20, 2026', status:'review'    },
    { title:'DevOps / Cloud Engineer',          company:'Sprout Solutions',       logoColor:'#059669', initials:'SS', date:'Mar 18, 2026', status:'interview' },
    { title:'UX / UI Designer',                 company:'Lamudi Philippines',      logoColor:'#16a34a', initials:'LP', date:'Mar 15, 2026', status:'pending'   },
    { title:'Data Analyst',                     company:'Globe Telecom',           logoColor:'#0284c7', initials:'GT', date:'Mar 12, 2026', status:'pending'   },
    { title:'Java Backend Developer',           company:'UnionBank',              logoColor:'#d97706', initials:'UB', date:'Mar 10, 2026', status:'accepted'  },
    { title:'Digital Marketing Specialist',     company:'Shopee Philippines',     logoColor:'#dc2626', initials:'SP', date:'Mar 8,  2026', status:'rejected'  },
    { title:'Content Writer & SEO Specialist',  company:'Summit Media Group',     logoColor:'#7c3aed', initials:'SM', date:'Mar 5,  2026', status:'pending'   },
    { title:'Senior Graphic Designer',          company:'Creative Spark Agency',  logoColor:'#ea580c', initials:'CS', date:'Feb 28, 2026', status:'pending'   },
  ],

  applicants: [
    { id:1,  name:'Maria Clara Reyes',    role:'Senior Frontend Developer', avatar:'https://i.pravatar.cc/150?img=47', location:'Quezon City',  skills:['Vue.js','React','TypeScript'],   exp:'4 yrs', status:'review'    },
    { id:2,  name:'Jose Miguel Cruz',     role:'DevOps / Cloud Engineer',   avatar:'https://i.pravatar.cc/150?img=32', location:'Makati City',  skills:['AWS','Docker','Kubernetes'],     exp:'5 yrs', status:'interview' },
    { id:3,  name:'Anna Liza Santos',     role:'UX / UI Designer',          avatar:'https://i.pravatar.cc/150?img=5',  location:'Pasig City',   skills:['Figma','User Research'],        exp:'3 yrs', status:'pending'   },
    { id:4,  name:'Ramon Dela Cruz',      role:'Senior Frontend Developer', avatar:'https://i.pravatar.cc/150?img=33', location:'Mandaluyong',  skills:['React','Next.js','Tailwind'],   exp:'6 yrs', status:'accepted'  },
    { id:5,  name:'Christine Macaraeg',   role:'Data Analyst',              avatar:'https://i.pravatar.cc/150?img=9',  location:'Taguig City',  skills:['SQL','Python','Tableau'],       exp:'2 yrs', status:'pending'   },
    { id:6,  name:'Paolo Fernandez',      role:'Java Backend Developer',    avatar:'https://i.pravatar.cc/150?img=51', location:'Ortigas',      skills:['Java','Spring Boot','MySQL'],   exp:'4 yrs', status:'review'    },
    { id:7,  name:'Bianca Morales',       role:'Digital Marketing',         avatar:'https://i.pravatar.cc/150?img=29', location:'Quezon City',  skills:['Google Ads','Meta','SEO'],      exp:'3 yrs', status:'pending'   },
    { id:8,  name:'Luis Domingo',         role:'Content Writer',            avatar:'https://i.pravatar.cc/150?img=55', location:'Mandaluyong',  skills:['SEO Writing','WordPress'],      exp:'2 yrs', status:'rejected'  },
    { id:9,  name:'Jasmine Tan',          role:'HR & Recruitment',          avatar:'https://i.pravatar.cc/150?img=21', location:'Pasay City',   skills:['Recruitment','HRIS'],           exp:'3 yrs', status:'pending'   },
    { id:10, name:'Kenneth Ocampo',       role:'DevOps / Cloud Engineer',   avatar:'https://i.pravatar.cc/150?img=61', location:'Taguig City',  skills:['AWS','Terraform','Linux'],      exp:'5 yrs', status:'review'    },
    { id:11, name:'Ella Pascual',         role:'UX / UI Designer',          avatar:'https://i.pravatar.cc/150?img=16', location:'Makati City',  skills:['Figma','Adobe XD','CSS'],       exp:'4 yrs', status:'interview' },
    { id:12, name:'Renzo Bautista',       role:'Senior Frontend Developer', avatar:'https://i.pravatar.cc/150?img=68', location:'BGC, Taguig',  skills:['Vue.js','TypeScript','GraphQL'],exp:'5 yrs', status:'pending'   },
  ],

  jsMessages: [
    { id:0, from:'TechBridge Philippines', avatar:'https://i.pravatar.cc/150?img=11', last:'Are you available Thursday at 2 PM?', time:'10:30 AM', unread:2, chat:[
      { out:false, text:'Hello! We reviewed your application for Senior Frontend Developer and we love your portfolio.',   time:'10:15 AM' },
      { out:true,  text:'Thank you so much! I\'m very excited about this opportunity.',                                   time:'10:20 AM' },
      { out:false, text:'We\'d love to schedule a technical interview this week.',                                         time:'10:25 AM' },
      { out:true,  text:'Yes — Thursday afternoon works perfectly for me!',                                                time:'10:28 AM' },
      { out:false, text:'Are you available Thursday at 2 PM?',                                                            time:'10:30 AM' },
    ]},
    { id:1, from:'Sprout Solutions', avatar:'https://i.pravatar.cc/150?img=25', last:'Please send us your updated resume.', time:'Yesterday', unread:0, chat:[
      { out:false, text:'Hi! We\'re reviewing your DevOps application. Could you share more about your AWS experience?',  time:'Yesterday 2:00 PM' },
      { out:true,  text:'Of course! I\'ve been working with AWS for 3 years — primarily EC2, EKS, and RDS.',             time:'Yesterday 3:00 PM' },
      { out:false, text:'Please send us your updated resume.',                                                             time:'Yesterday 4:00 PM' },
    ]},
    { id:2, from:'Lamudi Philippines', avatar:'https://i.pravatar.cc/150?img=17', last:'Thanks for applying!', time:'Mar 15', unread:0, chat:[
      { out:false, text:'Thanks for your application! Our team will review your portfolio shortly.',                       time:'Mar 15' },
      { out:true,  text:'Thank you! Looking forward to hearing back.',                                                     time:'Mar 15' },
    ]},
  ],

  empMessages: [
    { id:0, from:'Juniel Santos',    avatar:'https://i.pravatar.cc/150?img=47', role:'Senior Frontend Dev', last:'Thursday 2 PM works!', time:'10:30 AM', unread:1, chat:[
      { out:true,  text:'Hello Juniel! We reviewed your application and your portfolio is fantastic.',                    time:'10:00 AM' },
      { out:false, text:'Thank you so much! I\'m really excited about this opportunity.',                                 time:'10:05 AM' },
      { out:true,  text:'We\'d love to schedule a technical interview. Are you free this week?',                          time:'10:20 AM' },
      { out:false, text:'Thursday 2 PM works!',                                                                           time:'10:30 AM' },
    ]},
    { id:1, from:'Jose Miguel Cruz',  avatar:'https://i.pravatar.cc/150?img=32', role:'DevOps Engineer', last:'I have 5 years of AWS exp...', time:'9:15 AM', unread:0, chat:[
      { out:false, text:'Good morning! I applied for the DevOps role. 5 years of AWS experience, focused on EKS.',       time:'9:15 AM' },
      { out:true,  text:'Thanks Jose! We\'ll review your profile and be in touch soon.',                                  time:'9:30 AM' },
    ]},
    { id:2, from:'Ramon Dela Cruz',   avatar:'https://i.pravatar.cc/150?img=33', role:'Senior Frontend Dev', last:'Amazing news! Thank you!', time:'Yesterday', unread:0, chat:[
      { out:true,  text:'Hi Ramon! Congratulations — we\'d like to extend an offer for the Senior Frontend Developer position.', time:'Yesterday 3:00 PM' },
      { out:false, text:'Amazing news! Thank you!',                                                                        time:'Yesterday 3:30 PM' },
    ]},
  ],

  empJobs: [
    { id:1, title:'Senior Frontend Developer',      type:'Full Time', arr:'Hybrid',  apps:8,  posted:'Mar 1, 2026',  status:'active'  },
    { id:2, title:'DevOps / Cloud Engineer',         type:'Full Time', arr:'Remote',  apps:5,  posted:'Mar 5, 2026',  status:'active'  },
    { id:3, title:'Product Designer',               type:'Full Time', arr:'Hybrid',  apps:12, posted:'Feb 20, 2026', status:'active'  },
    { id:4, title:'Mobile Developer (React Native)', type:'Full Time', arr:'Remote',  apps:3,  posted:'Mar 10, 2026', status:'paused'  },
    { id:5, title:'QA Engineer',                    type:'Full Time', arr:'On-site', apps:7,  posted:'Feb 15, 2026', status:'active'  },
    { id:6, title:'Business Analyst',               type:'Full Time', arr:'Hybrid',  apps:9,  posted:'Jan 28, 2026', status:'closed'  },
    { id:7, title:'Data Scientist',                 type:'Full Time', arr:'Hybrid',  apps:6,  posted:'Mar 15, 2026', status:'active'  },
  ],
};